sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root


#minio对象存储
  minio:
    endpoint: http://127.0.0.1:9000
    access-key: admin
    secret-key: password
    bucket-name: img


  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10